#!/bin/bash

find _site -name '*.html' | while read file; do
    # we don't want warning from tidy about pigments empty span that will not be
    # fixed https://bitbucket.org/birkenfeld/pygments-main/issues/1254
    sed -i 's!<span></span>!!g' $file
    tidy --drop-proprietary-attributes true --show-warnings false --output-xhtml true -utf8 -indent -wrap 200 -modify -quiet "$file"
done
find _site -name '*.xml' | while read file; do
    tidy -xml -utf8 -indent -wrap 200 -modify -quiet "$file"
    sed -i 's/^<!\[CDATA\[/        <![CDATA[/g' "$file"
done
